<?php
/**
 * Implements hook_filter_info().
 */
function asciidoc_filter_info() {
  return array(
    'asciidoc_simple' => array(
      'title'            => t('AsciiDoc filter'),
      'description'      => t('Allows users to use AsciiDoc syntax.'),
      'process callback' => 'asciidoc_process_callback',
      'tips callback'    => 'asciidoc_filter_tips',
      'settings callback' => 'asciidoc_filter_settings_callback',
    ),
  );
}

/**
 * Implement hook_menu().
 */
function asciidoc_menu() {
  $items = array();
  
  $items['admin/config/content/formats/asciidoc'] = array(
    'title' => 'AciiDoc Filter',
    'description' => 'Configure the AsciiDoc filter.',
    'file' => 'asciidoc.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('asciidoc_config_form'),
    'access arguments' => array('administer filters'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Settings callback for the AsciiDoc filter.
 */
function asciidoc_filter_settings_callback($form, &$form_state, $filter, $format, $defaults, $filters) {
  require_once drupal_get_path('module', 'asciidoc') .'/asciidoc.admin.inc';
  return _asciidoc_filter_settings();
}

/**
 * Implements hook_filter_tips().
 */
function asciidoc_filter_tips($filter, $format, $long) {
  return t('You can use <a href="@user_guide">AsciiDoc syntax</a> to format 
      and style the text. For a quick reference see the <a href="@cheatsheet">
      cheatsheet</a>.', 
    array('@user_guide' => 'http://www.methods.co.nz/asciidoc/userguide.html', 
        '@cheatsheet' => 'http://powerman.name/doc/asciidoc')
    );
}

/**
 * Process callback for asciidoc_simple filter.
 *
 * @return
 *   As defined by hook_filter_FILTER_process().
 */
function asciidoc_process_callback($text, $filter, $format, $langcode, $cache, $cache_id) {
  if (empty($text)) {
    return '';
  }
  
  $asciidoc_highlight_library = variable_get('asciidoc_highlight_library');
  $asciidoc_pygments_path = variable_get('asciidoc_pygments_path');
  $asciidoc_asciidoc_path = variable_get('asciidoc_asciidoc_path');
  
  $command_str = 'echo %s | ';
  if ($asciidoc_highlight_library === 'Pygments') {
    // include the Pygments library in the PATH of the command
    if ($asciidoc_pygments_path !== '') {
      $command_str .= 'PATH=$PATH:' . $asciidoc_pygments_path;
    }
    
    // indicate to the Asciidoc that we are using the Pygments filter
    $command_str .= ' ' . $asciidoc_asciidoc_path . ' -a pygments';
  } else {
    $command_str .= $asciidoc_asciidoc_path; 
  }
  
  $command_str .= ' --no-header-footer -o - -';

  // we use basically asciidoc defaults: --doctype article --backend xhtml11
  $command = sprintf($command_str, escapeshellarg($text));
  exec(escapeshellcmd($command), $lines);
  $output = implode("\n", $lines);
  
  $output = "<div class='asciidoc'>\n" . $output . "\n</div>\n";

  return $output;
}
